version: 2.1
jobs:
  test:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          name: Activate virtualenv
          command: |
            pip install pipenv
            pipenv install
      - run:
          name: Setup env
          command: |
            echo "API_KEY=$SENDGRID_API_KEY" >> .env
            echo "TOS=alice@sink.sendgrid.net,bob@sink.sendgrid.net,carol@sink.sendgrid.net" >> .env
            echo "FROM=you@example.com" >> .env
      - run:
          name: Show versions
          command: |
            VER=$(cat Pipfile.lock | jq -r .default.sendgrid.version)
            echo "sendgrid-library: Version$VER"
            python --version
      - run:
          name: Unittest
          command: pipenv run test

workflows:
  version: 2
  normal_deploy_workflow:
    jobs:
      - test
  monthly_workflow:
    triggers:
      - schedule:
          cron: "0 0 2 * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - test