version: 2
jobs:
  build:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          command: |
            sudo pipenv install
            pipenv shell
            python -m unittest