version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          name: Activate virtualenv
          command: |
            pip install pipenv
            pipenv install
            pipenv shell
      - run:
          name: Unittest
          command: python -m unittest
      - run:
          name: Show versions
          command: |
            pip show sendgrid
            python --version