version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          name: unittest
          command: |
            pip install pipenv
            pipenv install
            pipenv shell
            python -m unittest
            pip show sendgrid
            python --version
          no_output_timeout: 30m